### ISSUE TITLE
РК №4

### ISSUE THREAD

**Issue by StealthTech** [frontend-park-mail-ru/2023_1_Seekers#9]
- [x] Регистрация. Ошибка на вводе логина не отражает суть проблемы
<img width="756" alt="image" src="https://github.com/frontend-park-mail-ru/2023_1_Seekers/assets/5190765/71182c0a-996b-4b38-b3ed-e46ae99103b7">

- [ ] Переделать страницу открытия аттача на что-нибудь приличное (напр. /attach/<hash>/preview/) https://mailbx.ru/api/v1/attach/37/preview
- [ ] Нужно организовать вёрстку для просмотра аттача
<img width="386" alt="image" src="https://github.com/frontend-park-mail-ru/2023_1_Seekers/assets/5190765/cd5f3e7b-4b7f-4a36-8e9c-aa47307c8842">

- [ ] Починить высоту iframe с отображением аттача
- [x] 404 не отображается нормально
- [x] Режется мягкий знак
<img width="193" alt="image" src="https://github.com/frontend-park-mail-ru/2023_1_Seekers/assets/5190765/44800eb2-fd28-4cd1-b3df-d7d4bbb1c7a3">

- [x] focusout в compose ломает список chip с emailами
- [x] пробел в конце email не режется 
<img width="234" alt="image" src="https://github.com/frontend-park-mail-ru/2023_1_Seekers/assets/5190765/5be73088-685c-49f9-8216-e0977617eac0">

- [x] zalgo ломает тему  
<img width="311" alt="image" src="https://github.com/frontend-park-mail-ru/2023_1_Seekers/assets/5190765/4830dc84-9b4e-4df8-be94-1f7f2b8f396f">

- [x] повысить гусеустойчивость
- [x] формат даты дд-мм-гггг
- [x] "упс" на большой файл — явно указать ограничение
- [x] не работает стабильно отправка и приём сообщений извне
- [ ] push-уведомления в браузере

**Comment by MoraPresence** [comment]
Наши правки:
[] Высвечивать получателя в исходящих
[] При добавлении нескольких аттачей - они множатся
[] В роутере если ссылка на внешний ресурс высвечивается 404(надо редиректить)
[] Отбтвка на перссылку писем
[] Фильт все еще не работает
[] При перессылке не подгружаются вложения

**Comment by StealthTech** [comment]
Зачтено частично, т.к. не все пункты закрыты. Не зачтено:
- [ ] Переделать страницу открытия аттача на что-нибудь приличное (напр. /attach//preview/) https://mailbx.ru/api/v1/attach/37/preview
- [ ] Нужно организовать вёрстку для просмотра аттача
- [ ] Починить высоту iframe с отображением аттача
- [ ] push-уведомления в браузере
